### ISSUE TITLE
Error file not found when executing

### ISSUE THREAD

**Issue by jknight2014** [KenV99/service.kodi.callbacks#5]
Having an issue with the python library this is trying to use on LibreELEC 8.0.0 Kodi 17.1 RC1.

```
ERROR: $$$ [kodi.callbacks] - ERROR encountered for Task T1, Event onIdle:E1
                                            ERROR mesage: <attribute 'message' of 'exceptions.BaseException' objects>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/tasks/taskScript.py", line 159, in run
                                                p = subprocess.Popen(args, stdout=subprocess.PIPE, shell=needs_shell, stderr=subprocess.STDOUT, cwd=basedir)
                                              File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
                                              File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
                                            OSError: [Errno 2] No such file or directory
```

**Comment by tmds** [comment]
This is still an issue:

```
2019-11-16 12:36:52.087 T:1373623168   ERROR: $$$ [kodi.callbacks] - Testing for task type: script
                                            Settings: {u'use_shell': False, 'notify': False, u'scriptfile': u'/storage/on_playback_start', 'taskid': u'T1', 'userargs': u'', 'type': u'script', u'waitForCompletion': True}
                                            Runtime kwargs: {'width': '1080', 'aspectRatio': '2.35', 'title': 'Star Wars Episode IV - A New Hope', 'mediaType': 'movie', 'fileName': 'G:\\movies\\Star Wars - Episode IV\\movie.mkv'}
                                            ERROR encountered for Task T1, Event onPlayBackStarted
                                            ERROR mesage: <attribute 'message' of 'exceptions.BaseException' objects>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/tasks/taskScript.py", line 159, in run
                                                p = subprocess.Popen(args, stdout=subprocess.PIPE, shell=needs_shell, stderr=subprocess.STDOUT, cwd=basedir)
                                              File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
                                              File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
                                            OSError: [Errno 2] No such file or directory
```

toggling use_shell doesn't help find the script:

```
2019-11-16 12:40:47.980 T:1799328640  NOTICE: $$$ [kodi.callbacks] - Testing for task type: script
                                            Settings: {u'use_shell': True, 'notify': False, u'scriptfile': u'/storage/on_playback_start', 'taskid': u'T1', 'userargs': u'', 'type': u'script', u'waitForCompletion': True}
                                            Runtime kwargs: {'width': '1080', 'aspectRatio': '2.35', 'title': 'Star Wars Episode IV - A New Hope', 'mediaType': 'movie', 'fileName': 'G:\\movies\\Star Wars - Episode IV\\movie.mkv'}
                                            Command for Task T1, Event onPlayBackStarted completed succesfully!
                                            The following message was returned: taskScript ARGS = on_playback_start
                                                SYSEXEC = None
                                             BASEDIR = /storage
                                            Process returned data: [/bin/sh: on_playback_start: not found]
```

Also, lots of parsing errors show up in the log:
```
...
2019-11-16 12:40:47.820 T:1799328640 WARNING: CAddonSettings[script.service.kodi.callbacks]: failed to parse visible condition "eq(-81,32241)" of old setting definition for "E8.rejectIf"
2019-11-16 12:40:47.826 T:1799328640 WARNING: CAddonSettings[script.service.kodi.callbacks]: cannot reference separator setting in old setting condition "eq(-80,32241)" for "E9.matchIf"
2019-11-16 12:40:47.826 T:1799328640 WARNING: CAddonSettings[script.service.kodi.callbacks]: failed to parse visible condition "eq(-80,32241)" of old setting definition for "E9.matchIf"
2019-11-16 12:40:47.826 T:1799328640 WARNING: CAddonSettings[script.service.kodi.callbacks]: cannot reference separator setting in old setting condition "eq(-81,32241)" for "E9.rejectIf"
2019-11-16 12:40:47.826 T:1799328640 WARNING: CAddonSettings[script.service.kodi.callbacks]: failed to parse visible condition "eq(-81,32241)" of old setting definition for "E9.rejectIf"
2019-11-16 12:40:47.833 T:1799328640 WARNING: CAddonSettings[script.service.kodi.callbacks]: cannot reference separator setting in old setting condition "eq(-80,32241)" for "E10.matchIf"
2019-11-16 12:40:47.833 T:1799328640 WARNING: CAddonSettings[script.service.kodi.callbacks]: failed to parse visible condition "eq(-80,32241)" of old setting definition for "E10.matchIf"
2019-11-16 12:40:47.833 T:1799328640 WARNING: CAddonSettings[script.service.kodi.callbacks]: cannot reference separator setting in old setting condition "eq(-81,32241)" for "E10.rejectIf"
2019-11-16 12:40:47.833 T:1799328640 WARNING: CAddonSettings[script.service.kodi.callbacks]: failed to parse visible condition "eq(-81,32241)" of old setting definition for "E10.rejectIf"
...
```
