### ISSUE TITLE
Not working with Kodi19/Python3

### ISSUE THREAD

**Issue by kafisc1** [KenV99/service.kodi.callbacks#8]
Any chance this will work with Kodi19?
Seems to be broken with the newly added Python3.

2019-11-08 17:19:40.735 T:11132   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ModuleNotFoundError'>
                                            Error Contents: No module named 'tasks'
                                            Traceback (most recent call last):
                                              File "C:\Users\claus\AppData\Roaming\Kodi\addons\script.service.kodi.callbacks\script.py", line 25, in <module>
                                                import resources.lib.pubsub as PubSub_Threaded
                                              File "C:\Users\claus\AppData\Roaming\Kodi\addons\script.service.kodi.callbacks\resources\lib\__init__.py", line 23, in <module>
                                                import tasks
                                            ModuleNotFoundError: No module named 'tasks'
                                            -->End of Python script error report<--
2019-11-08 17:20:05.307 T:7804   ERROR: Previous line repeats 3 times.
                              
Please see here for more informations:
https://forum.kodi.tv/showthread.php?tid=343068&pid=2896044#pid2896044

Thank you in advance

**Comment by tbertels** [comment]
Original developer seems inactive, see https://github.com/pikim/script.service.kodi.callbacks for most current fork.
